export const GET_CATEGORIES = 'GET_CATEGORIES'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'

export const ALL_TRANSACTIONS = 'ALL_TRANSACTIONS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const MY_TRANSACTIONS = 'MY_TRANSACTIONS'
export const SEND_MONEY = 'SEND_MONEY'
export const GET_BALANCE = 'GET_BALANCE'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
